const fases = [
  "Estou ótimo!",
  "Tudo certo!",
  "Estou muito bem, obrigado!",
  "Beleza pura!",
  "Tudo tranquilo!",
  "Estou bem e você?",
  "Estou de boa!",
  "Não poderia estar melhor!",
  "Estou firme e forte!",
  "Na paz!",
  "Tudo nos conformes!",
  "Estou maravilhosamente bem!",
  "Nada a reclamar!",
  "Estou sussa!",
  "Estou zen!",
  "Só alegria!",
  "Vivendo e aprendendo!",
  "Tô na atividade!",
  "Suave na nave!",
  "De vento em popa!",
  "100%!",
  "Melhor impossível!",
  "Super bem!",
  "Maravilha!",
  "Na tranquilidade!",
  "De boa na lagoa!",
  "Sempre em frente!",
  "Com tudo em cima!",
  "Estou voando!",
  "Tudo fluindo!",
  "Radiante!",
  "No auge!",
  "Tudo indo bem!",
  "No topo!",
  "Mais feliz impossível!",
  "De bem com a vida!",
  "Com a energia lá em cima!",
  "Só sucesso!",
  "Na melhor vibe!",
  "Feliz da vida!",
  "No modo gratidão!",
  "Sorrindo à toa!",
  "Animado como nunca!",
  "Tô brilhando!",
  "Em plena forma!",
  "Tô no gás!",
  "A vida tá linda!",
  "No embalo certo!",
  "Tô no flow!",
  "Caminhando firme!",
  "Como está o clima aí?",
  "Tá frio ou calor hoje?",
  "O tempo está bom?",
  "Vai chover hoje?",
  "Como está a previsão do tempo?",
  "O sol apareceu por aí?",
  "Tá ventando muito?",
  "O dia tá bonito?",
  "Preciso levar guarda-chuva?",
  "Tá um tempo agradável?",
  "O céu está limpo?",
  "Como está a temperatura agora?",
  "Está muito úmido?",
  "Vai esfriar mais tarde?",
  "Tem previsão de tempestade?",
  "O tempo tá firme?",
  "Tá um dia ensolarado?",
  "Tá muito abafado hoje?",
  "Como está o clima pela manhã?",
  "E à noite, vai esfriar?",
  "Está chovendo agora?",
  "O tempo tá fechado?",
  "O calor tá demais aí?",
  "O vento tá forte?",
  "Dá pra sair sem casaco?",
  "A umidade tá alta?",
  "O tempo mudou de repente?",
  "Tá aquele mormaço chato?",
  "Tem neblina hoje?",
  "O sol tá forte?",
  "Tem previsão de neve?",
  "O clima tá seco?",
  "Vai ventar muito hoje?",
  "O tempo está instável?",
  "Tá uma delícia de clima?",
  "Tá aquele friozinho gostoso?",
  "Como está o céu agora?",
  "Dá pra pegar praia hoje?",
  "Vai fazer sol o dia todo?",
  "Tá uma temperatura boa pra sair?",
  "Preciso levar casaco?",
  "O tempo tá estranho hoje?",
  "Tem previsão de trovoada?",
  "Tá aquele calor insuportável?",
  "A temperatura caiu bastante?",
  "O dia amanheceu bonito?",
  "A noite vai ser fria?",
  "Como tá o tempo aí na sua cidade?",
  "O clima tá agradável pra um passeio?",
  "Tá aquele ventinho gostoso?",
  "Não estou nada bem!",
    "Tudo errado!",
    "Não estou nada bem, obrigado!",
    "Nada de beleza!",
    "Tudo turbulento!",
    "Não estou bem e você?",
    "Não estou de boa!",
    "Poderia estar pior!",
    "Não estou firme nem forte!",
    "Sem paz!",
    "Tudo fora dos conformes!",
    "Estou péssimo!",
    "Tenho muito a reclamar!",
    "Não estou sussa!",
    "Estou estressado!",
    "Nenhuma alegria!",
    "Só vivendo, mas sem aprender!",
    "Tô sem energia!",
    "Nada suave na nave!",
    "De vento contra!",
    "0%!",
    "Pior impossível!",
    "Super mal!",
    "Um desastre!",
    "Na inquietação!",
    "De tenso na lama!",
    "Sempre pra trás!",
    "Tudo caindo!",
    "Estou afundando!",
    "Nada fluindo!",
    "Opaco!",
    "No fundo do poço!",
    "Tudo indo mal!",
    "Lá embaixo!",
    "Mais triste impossível!",
    "De mal com a vida!",
    "Com a energia lá embaixo!",
    "Só fracasso!",
    "Na pior vibe!",
    "Triste da vida!",
    "No modo desespero!",
    "Chorando à toa!",
    "Desanimado como nunca!",
    "Tô apagado!",
    "Fora de forma!",
    "Tô sem gás!",
    "A vida tá horrível!",
    "No embalo errado!",
    "Tô travado!",
    "Caminhando sem rumo!",
    "Como está o clima aí? Deve estar horrível!",
    "Tá um tempo péssimo, né?",
    "O tempo está horrível?",
    "Vai ficar seco o dia todo?",
    "A previsão do tempo tá ruim?",
    "O sol nem apareceu por aí?",
    "Tá sem vento nenhum?",
    "O dia tá feio?",
    "Nem precisa de guarda-chuva, não chove nunca!",
    "Tá um tempo desagradável?",
    "O céu está nublado?",
    "Como está a temperatura agora? Fria demais?",
    "Está seco demais?",
    "Não vai esfriar mais tarde?",
    "Sem previsão de tempestade?",
    "O tempo tá instável?",
    "Tá um dia nublado?",
    "Nada abafado hoje?",
    "Como está o clima pela manhã? Ruim?",
    "E à noite, nem vai esfriar?",
    "Não está chovendo agora?",
    "O tempo tá aberto?",
    "Nem tem calor aí?",
    "O vento sumiu?",
    "Nem dá pra sair sem casaco!",
    "A umidade tá baixa?",
    "O tempo continua igual?",
    "Nem tá aquele mormaço chato?",
    "Nenhuma neblina hoje?",
    "O sol nem apareceu?",
    "Não tem previsão de neve?",
    "O clima tá super úmido?",
    "Nem um ventinho hoje?",
    "O tempo está estável demais?",
    "Tá um clima péssimo?",
    "Nem aquele friozinho gostoso?",
    "O céu tá escuro?",
    "Nem dá pra pegar praia hoje!",
    "Vai ficar nublado o dia todo?",
    "Tá uma temperatura horrível pra sair?",
    "Nem precisa levar casaco?",
    "O tempo tá normal hoje?",
    "Sem previsão de trovoada?",
    "Nem tá aquele calorzão insuportável?",
    "A temperatura continua a mesma?",
    "O dia amanheceu nublado?",
    "A noite vai ser quente?",
    "O clima na sua cidade tá ruim?",
    "O clima tá horrível pra um passeio?",
    "Nem aquele ventinho gostoso?"
];

module.exports = { fases };